repurposed_key_item_ids = [
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    155,
    156,
    157,
    158,
    159,
    160,
    161,
    162,
    163,
    164,
    165,
    166,
    167,
    230,
    231,
    232,
    233,
    234,
    235,
    236,
    237,
    238,
    239,
    240,
    241,
    242,
    243,
    244,
    245,
    246,
    247,
    248,
    249,
    250,
    251,
    252,
    253,
    254,
    255
]

sora_ability_item_ids = [
    2643005,
    2643006,
    2643007,
    2643008,
    2643010,
    2643011,
    2643012,
    2643013,
    2643014,
    2643015,
    2643016,
    2643017,
    2643018,
    2643019,
    2643020,
    2643021,
    2643022,
    2643023,
    2643024,
    2643025,
    2643026,
    2643027,
    2643028,
    2643053,
    2643054,
    2643055,
    2643056,
    2643057,
    2643058,
    2643059,
    2643060,
    2643061,
    2643062,
    2643064,
    2643065,
]

kh1_hex_to_char_map = [
    "{eol}",
    " ",
    "{lf}",
    "{0x03}",
    "{0x04}",
    "{0x05}",
    "{0x06}",
    "{0x07}",
    "{0x08}",
    "{0x09}",
    "{0x0A}",
    "{0x0B}",
    "{0x0C}",
    "{0x0D}",
    "{0x0E}",
    "{0x0F}",
    "{0x10}",
    "{0x11}",
    "{0x12}",
    "{0x13}",
    "{0x14}",
    "{0x15}",
    "{0x16}",
    "{0x17}",
    "{0x18}",
    "{0x19}",
    "{0x1A}",
    "{0x1B}",
    "{0x1C}",
    "{0x1D}",
    "{0x1E}",
    "{0x1F}",
    "—",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "!",
    "?",
    "&",
    "%",
    "+",
    "{-}",
    "{mX}",
    "/",
    "*",
    ".",
    ",",
    "・",
    ":",
    ";",
    "…",
    "-",
    "ー",
    "~",
    "'",
    "\"",
    "{゛b}",
    "(",
    ")",
    "[",
    "]",
    "<",
    ">",
    "★",
    "☆",
    "↑",
    "↓",
    "→",
    "←",
    "●",
    "■",
    "{iPotion}",
    "{iTent}",
    "{iGem}",
    "{iAbility}",
    "{iKey}",
    "{iStaff}",
    "{iShield}",
    "{iRing}",
    "{iHat}",
    "{iMickey}",
    "○",
    "×",
    "△",
    "□",
    "▲",
    "▼",
    "►",
    "◄",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{iGumm",
    "{0x9E}",
    "{0x9F}",
    "{0xA0}",
    "{0xA1}",
    "{0xA2}",
    "{0xA3}",
    "{0xA4}",
    "{0xA5}",
    "{0xA6}",
    "{0xA7}",
    "{0xA8}",
    "®",
    "{0xAA}",
    "{0xAB}",
    "{0xAC}",
    "{0xAD}",
    "{0xAE}",
    "{0xAF}",
    "{0xB0}",
    "{0xB1}",
    "{0xB2}",
    "{0xB3}",
    "{0xB4}",
    "{0xB5}",
    "{0xB6}",
    "{0xB7}",
    "{0xB8}",
    "{0xB9}",
    "{0xBA}",
    "{0xBB}",
    "{0xBC}",
    "{0xBD}",
    "{0xBE}",
    "{0xBF}",
    "{0xC0}",
    "{0xC1}",
    "{0xC2}",
    "{0xC3}",
    "{III}",
    "{VII}",
    "{VIII}",
    "{X}",
    "Œ",
    "œ",
    "¡",
    "¿",
    "À",
    "Á",
    "Â",
    "Ä",
    "Ç",
    "È",
    "É",
    "Ê",
    "Ë",
    "Ì",
    "Í",
    "Î",
    "Ï",
    "Ñ",
    "Ò",
    "Ó",
    "Ô",
    "Ö",
    "Ù",
    "Ú",
    "Û",
    "Ü",
    "ß",
    "à",
    "á",
    "â",
    "ä",
    "ç",
    "è",
    "é",
    "ê",
    "ë",
    "ì",
    "í",
    "î",
    "ï",
    "ñ",
    "ò",
    "ó",
    "ô",
    "ö",
    "ù",
    "ú",
    "û",
    "ü",
    "°",
    "{---}",
    "》",
    "《",
    "{0xFD}",
    "{0xFE}",
    "{0xFF}"
]

new_item_descriptions = {
    9: "Allows progression in 100 Acre Wood.",
    149: "Allows travel to Wonderland.",
    150: "Allows travel to Olympus Coliseum.",
    151: "Allows travel to Deep Jungle.",
    155: "Allows travel to Agrabah.",
    156: "Allows travel to Monstro.",
    157: "Allows travel to Atlantica.",
    165: "Allows travel to Neverland.",
    166: "Allows travel to Halloween Town.",
    167: "Puppies to return in Traverse Town.\nMultiplied by your definied puppy value in settings.",
    168: "Allows travel to Hollow Bastion.",
    169: "Allows travel to End of the World.",
    170: "Allows interaction with Blue Trinity marks.",
    171: "Allows interaction with Red Trinity marks.",
    172: "Allows interaction with Green Trinity marks.",
    173: "Allows interaction with Yellow Trinity marks.",
    174: "Allows interaction with White Trinity marks.",
    175: "Allows Sora and Donald to cast Fire.\nAcquire more to increase level.",
    176: "Allows Sora and Donald to cast Blizzard.\nAcquire more to increase level.",
    177: "Allows Sora and Donald to cast Thunder.\nAcquire more to increase level.",
    178: "Allows Sora and Donald to cast Cure.\nAcquire more to increase level.",
    179: "Allows Sora and Donald to cast Gravity.\nAcquire more to increase level.",
    180: "Allows Sora and Donald to cast Stop.\nAcquire more to increase level.",
    181: "Allows Sora and Donald to cast Aero.\nAcquire more to increase level.",
    182: "Allows entrance to the Phil Cup.",
    183: "Allows access to the upper floor\nin Hollow Bastion Entrance Hall.",
    184: "Allows entrance to the Pegasus Cup.",
    185: "Allows entrance to the Hercules Cup.",
    186: "Used for item synthesis in Traverse Town.",
    188: "Used to progress in Hollow Bastion.",
    189: "Used to progress in Hollow Bastion.",
    190: "Used to progress in Hollow Bastion.",
    191: "Used to progress in Hollow Bastion.",
    210: "Used to progress in Atlantica.",
    211: "Drop in Traverse Town mailbox.",
    217: "Used to progress in Deep Jungle.",
    218: "Used to progress in Deep Jungle.",
    219: "Used to progress in Deep Jungle.",
    220: "Used to progress in Deep Jungle.",
    221: "Used to progress in Deep Jungle.",
    222: "Used to progress in Deep Jungle.",
    223: "Used to progress in Wonderland.",
    227: "Used to progress in Halloween Town.",
    228: "Used to progress in Halloween Town.",
    229: "Used to progress in Olympus Coliseum.",
    230: "A placeholder for a remote item.\nThe item can be for you or someone else.",
    231: "Allows summoning Dumbo.",
    233: "Allows summoning Bambi.",
    234: "Allows summoning Genie.",
    235: "Allows summoning Tinker Bell.",
    236: "Allows summoning Mushu.",
    237: "Allows summoning Simba.",
    238: "A macguffin.\nSomething will happen if you acquire enough."
    }

keyblade_list = [
      "Kingdom Key"
    , "Dream Sword"
    , "Dream Shield"
    , "Dream Rod"
    , "Wooden Sword"
    , "Jungle King"
    , "Three Wishes"
    , "Fairy Harp"
    , "Pumpkinhead"
    , "Crabclaw"
    , "Divine Rose"
    , "Spellbinder"
    , "Olympia"
    , "Lionheart"
    , "Metal Chocobo"
    , "Oathkeeper"
    , "Oblivion"
    , "Lady Luck"
    , "Wishing Star"
    , "Ultima Weapon"
    , "Diamond Dust"
    , "One-Winged Angel"
]