from gooey import Gooey,GooeyParser
from write_mod import write_mod
import os

@Gooey(program_name='KH1 Randomizer Mod Generator',
        image_dir='./Images/',
        header_bg_color="#efcf78")

def main():
    parser = GooeyParser()
    
    parser.add_argument("ap_zip_file",
        widget = "FileChooser",
        metavar = "AP Zip File Output",
        help = "The zip file generated by Archipelago or the Seed Generator.")
    parser.add_argument("kh1_data_path",
        widget = "DirChooser",
        metavar = "KH1 Data Path",
        help = "The path to your KH1 data extracted by OpenKH.")
    
    args = parser.parse_args()
    write_mod(args.ap_zip_file, args.kh1_data_path)

if __name__ == "__main__":
    main()
